services:
  - type: web
    name: fastapi-book-project
    env: docker
    plan: free
    buildCommand: docker build -t fastapi-app .
    startCommand: docker run -p $PORT:80 fastapi-app
    envVars:
      - key: PORT
        value: 80 