# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t fastapi-app .

      # 5. Push Docker image to Docker Hub
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag fastapi-app anavheoba/fastapi-book-project:latest
          docker push anavheoba/fastapi-book-project:latest

      # 6. SSH into the server and deploy (not needed for Railway)
      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker pull anavheoba/fastapi-book-project:latest
      #       docker stop fastapi-app || true
      #       docker rm fastapi-app || true
      #       docker run -d --name fastapi-app --restart unless-stopped -p 8000:8000 anavheoba/fastapi-book-project:latest